--TABLES
CREATE TABLE PERSON 
(
  PERSON_ID INT GENERATED ALWAYS AS IDENTITY NOT NULL 
, FIRSTNAME VARCHAR2(50) 
, LASTNAME VARCHAR2(50) 
, CONSTRAINT PERSON_PK PRIMARY KEY 
  (
    PERSON_ID 
  )
  ENABLE 
);


CREATE TABLE TRIP 
(
  TRIP_ID INT GENERATED ALWAYS AS IDENTITY NOT NULL 
, NAME VARCHAR2(100) 
, COUNTRY VARCHAR2(50) 
, TRIP_DATE DATE
, NO_PLACES INT
, CONSTRAINT TRIP_PK PRIMARY KEY 
  (
    TRIP_ID 
  )
  ENABLE 
);



CREATE TABLE RESERVATION 
(
  RESERVATION_ID INT GENERATED ALWAYS AS IDENTITY NOT NULL 
, TRIP_ID INT 
, PERSON_ID INT 
, STATUS CHAR(1)
, CONSTRAINT RESERVATION_PK PRIMARY KEY 
  (
    RESERVATION_ID
  )
  ENABLE 
);


ALTER TABLE RESERVATION
ADD CONSTRAINT RESERVATION_FK1 FOREIGN KEY
(
  PERSON_ID 
)
REFERENCES PERSON
(
  PERSON_ID 
)
ENABLE;

ALTER TABLE RESERVATION
ADD CONSTRAINT RESERVATION_FK2 FOREIGN KEY
(
  TRIP_ID 
)
REFERENCES TRIP
(
  TRIP_ID 
)
ENABLE;

ALTER TABLE RESERVATION
ADD CONSTRAINT RESERVATION_CHK1 CHECK 
(status IN ('N','P','C'))
ENABLE;
